layout_spectrum: 0
color:
  saturation: 0.7688172
  lightness: 0.3673835
  brandStrength: 0.3799283
  brandColors:
    - '#24282B'
    - '#44FE01'
    - '#5D75FD'
    - '#FFFFFF'
    - '#F04B8F'
  rhythmicContrast: 0.7598566
typography_spectrum: 0.5698925
name: why worry wonder
